version: 0.0
os: linux
# 폴더경로는 원하는 곳에 하시면 됩니다.
files:
  - source: /
    destination: /home/ubuntu/front
    overwrite: yes
permissions:
  - object: /home/ubuntu/front
    owner: root
    group: root
    mode: 755
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root
